"""English resume payload (validated into Resume in main)."""

RESUME_EN_DICT = {
    "name": "Haoyang",
    "email": "songhaoyang2004@qq.com",
    "phone": None,
    "location": "Suzhou Industrial Park, China",
    "location_url": "https://www.google.com/maps/search/?api=1&query=Suzhou+Industrial+Park%2C+China",
    "tagline": "3+ years of coding",
    "education": [
        {
            "school": "Carnegie Mellon University",
            "school_url": "https://www.cmu.edu/",
            "degree": "Master of Information Systems Management (MISM)",
            "degree_url": "https://www.heinz.cmu.edu/programs/information-systems-management-master/",
            "place": "Pittsburgh, Pennsylvania, United States",
            "time": "Aug 2026 – Dec 2027 (expected)",
            "courses": [
                {"name": "Database management", "url": "https://en.wikipedia.org/wiki/Database"},
                {"name": "Distributed systems", "url": "https://en.wikipedia.org/wiki/Distributed_computing"},
                {"name": "Cloud computing", "url": "https://en.wikipedia.org/wiki/Cloud_computing"},
                {"name": "Data analytics", "url": "https://en.wikipedia.org/wiki/Data_analysis"},
                {"name": "Machine learning", "url": "https://en.wikipedia.org/wiki/Machine_learning"},
                {"name": "IT project management", "url": "https://en.wikipedia.org/wiki/Project_management"},
            ],
        },
        {
            "school": "Xi'an Jiaotong-Liverpool University (XJTLU)",
            "school_url": "https://www.xjtlu.edu.cn/en",
            "degree": "B.Sc. in Information and Computing Science",
            "degree_url": "https://www.xjtlu.edu.cn/en/study/undergraduate/information-and-computing-science",
            "place": "Suzhou, Jiangsu, China",
            "time": "Sep 2022 – Jun 2026",
            "courses": [
                {"name": "Linear algebra", "url": "https://en.wikipedia.org/wiki/Linear_algebra"},
                {"name": "Multivariate calculus", "url": "https://en.wikipedia.org/wiki/Multivariable_calculus"},
                {
                    "name": "Discrete mathematics & statistics",
                    "url": "https://en.wikipedia.org/wiki/Discrete_mathematics",
                },
                {"name": "Data structures", "url": "https://en.wikipedia.org/wiki/Data_structure"},
                {"name": "Computer systems", "url": "https://en.wikipedia.org/wiki/Computer_architecture"},
                {"name": "Java", "url": "https://en.wikipedia.org/wiki/Java_(programming_language)"},
                {"name": "Artificial intelligence", "url": "https://en.wikipedia.org/wiki/Artificial_intelligence"},
                {"name": "Software engineering", "url": "https://en.wikipedia.org/wiki/Software_engineering"},
                {"name": "Computer graphics", "url": "https://en.wikipedia.org/wiki/Computer_graphics"},
            ],
        },
    ],
    "experience": [
        {
            "company": "Tianyu Digital Technology",
            "company_url": "https://www.tianyushuke.com/",
            "role": "Game backend / Unity intern",
            "time": "Jun 2025 – Sep 2025",
            "description": [
                "Implemented backend logic for a Souls-like ARPG using Unity",
                "Implemented and debugged finite state machines for character behaviour",
                "Built a motion capture & generation pipeline with Python and MediaPipe",
                "Created an NLP-driven text-to-motion library",
                "Designed digital human models and animation workflows in Unreal Engine 5",
            ],
        },
        {
            "company": "Nanjing Hydraulic Research Institute — Hydraulics Division",
            "company_url": "https://www.nhri.cn/",
            "role": "Data analytics intern",
            "time": "Jun 2024 – Sep 2024",
            "description": [
                "Maintained and optimised the Jinji Lake digital twin system",
                "Monitored water quality and recorded key indicators",
                "Performed spatial analysis with GIS tools",
                "Analysed and forecasted data with Python and MATLAB",
                "Wrote data-cleaning scripts to improve data quality",
            ],
        },
    ],
    "projects": [
        {
            "name": "Video pose recognition & keyword matching API (FastAPI)",
            "role": "Solo developer",
            "period": "Apr 2026 – present",
            "description": [
                "Shipped a FastAPI service with video upload, pose extraction, async jobs, and OpenAPI docs at /docs",
                "Used MediaPipe for 33-point pose tracks with an automatic fallback extractor",
                "Cosine-similarity classification against per-class template vectors, updatable via video training",
                "Combined jieba, TF-IDF, and cosine similarity for class name and keyword retrieval",
                "SQLite and local files for uploads, keypoints, and features, with a static demo UI",
            ],
            "link": "http://116.62.55.74:8000/",
        },
        {
            "name": "ChatPDF — LLM-powered intelligent Q&A for PDFs",
            "role": "System administrator",
            "period": "Jun 2024 – Jul 2024",
            "description": [
                "Built a PDF Q&A tool on Gemini and LLaMA",
                "Delivered full-stack UI with Python and Streamlit",
                "Extracted PDF text with PyMuPDF",
                "Compared model behaviour in academic vs general scenarios",
            ],
            "link": "https://chatpdf2surf.streamlit.app",
        },
        {
            "name": "Meeting room management system (full stack)",
            "role": "Core developer",
            "period": "Apr 2025 – May 2025",
            "description": [
                "Owned end-to-end design: auth, room management, booking, email verification, RBAC",
                "Built the frontend with HTML, CSS, JavaScript and AJAX",
                "Structured backend with Spring Boot and MVC for maintainability",
                "Implemented validation, room search, and booking conflict checks",
                "Designed MySQL schema for consistency and efficient access",
            ],
            "link": None,
        },
    ],
    "skills": [
        {"name": "Python", "url": "https://www.python.org/"},
        {"name": "Java", "url": "https://dev.java/"},
        {"name": "MATLAB", "url": "https://www.mathworks.com/products/matlab.html"},
        {"name": "C++", "url": "https://isocpp.org/"},
        {"name": "SQL", "url": "https://en.wikipedia.org/wiki/SQL"},
        {"name": "Spring Boot", "url": "https://spring.io/projects/spring-boot"},
        {"name": "Streamlit", "url": "https://streamlit.io/"},
        {"name": "FastAPI", "url": "https://fastapi.tiangolo.com/"},
        {"name": "HTML", "url": "https://developer.mozilla.org/en-US/docs/Web/HTML"},
        {"name": "CSS", "url": "https://developer.mozilla.org/en-US/docs/Web/CSS"},
        {"name": "AJAX", "url": "https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX"},
        {"name": "PyMuPDF", "url": "https://pymupdf.readthedocs.io/"},
        {"name": "GIS tools", "url": "https://en.wikipedia.org/wiki/Geographic_information_system"},
        {"name": "LLM APIs (Gemini, LLaMA)", "url": "https://en.wikipedia.org/wiki/Large_language_model"},
        {"name": "Cursor", "url": "https://cursor.com/"},
        {"name": "Codex", "url": "https://openai.com/codex/"},
    ],
    "language": "IELTS 7.0 — strong English for academic work and technical reading",
    "publications": [
        "Ma, D., & haoyang.s (2023). Comparing cat–dog image classification across models. "
        "International Conference on Machine Learning and Automation (CONF-MLA 2023).",
    ],
    "campus": [
        {
            "org": "XJTLU — B.Sc. Information and Computing Science",
            "role": "Class monitor",
            "time": "Sep 2023 – present",
            "description": [
                "Bridged students and faculty with regular meetings",
                "Organised class activities (team building, outings)",
                "Supported peers academically",
                "First prize, university Leadership Challenge",
            ],
        },
    ],
}
